### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by new-village** [new-village/tabeloader#11]
`_is_available_booking`で`AttributeErrorが発生。
```
お好み焼き 百名店.csvをダウンロード開始
Traceback (most recent call last):
  File "C:\work\tabeloader_batch\tabeloader_batch.py", line 10, in <module>
    details = tabeloader.load_restaurant_details(restaurants)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\tabeloader_batch\.venv\Lib\site-packages\tabeloader-0.8-py3.12.egg\tabeloader\load.py", line 53, in load_restaurant_details       
  File "C:\work\tabeloader_batch\.venv\Lib\site-packages\tabeloader-0.8-py3.12.egg\tabeloader\load.py", line 262, in create_restaurant_details    
  File "C:\work\tabeloader_batch\.venv\Lib\site-packages\tabeloader-0.8-py3.12.egg\tabeloader\load.py", line 177, in _is_available_booking        
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by new-village** [comment]
エラーの原因は、[お好み焼き　ほり](https://tabelog.com/okayama/A3305/A330501/33000402/) のような、予約可否が無いケース。
